language: node_js
node_js: "8"
install: npm install
cache:
  directories:
  - dist

jobs:
  include:
    - stage: build
      node_js: "8"
      script: 
        - npm run lint 
        - npm run test
        - npm run build
        - npm install nsp -g
        - nsp check
    - stage: release
      node_js: "8"
      if: branch = master AND type = push
      script: npm run semantic-release
